# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='where',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='achievement',
            name='short_description',
            field=models.CharField(max_length=200),
        ),
    ]
