# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20160502_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='what',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
