# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_achievement_what'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
