# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_skill_fa_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
