# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-03 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_publication_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='fa_string',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
