# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_education_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='value',
            field=models.CharField(max_length=200),
        ),
    ]
