# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-01 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('os', models.CharField(max_length=200)),
                ('sdk', models.CharField(max_length=200)),
                ('device', models.CharField(max_length=200)),
                ('build', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField()),
            ],
        ),
    ]
