# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='is_pro',
            field=models.BooleanField(default=False),
        ),
    ]
