# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 10:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquest', '0002_userinfo_is_pro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='build',
            new_name='model',
        ),
    ]
