# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-04 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquest', '0003_auto_20160604_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='last_ping',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='model',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='os',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='sdk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
